apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: simple-web-app-hostrule
spec:
  virtualhost:
    fqdn: simple-web.demo.corp.tanzu # mandatory
    fqdnType: Exact
    enableVirtualHost: true

    tls: # optional
      sslKeyCertificate:
        name: demo-corp-tanzu-wildcard-cert
        type: ref
      sslProfile: System-Standard-PFS
      termination: edge
    # gslb:
    #   fqdn: foo.com
    # httpPolicy:
    #   policySets:
    #   - avi-secure-policy-ref
    #   overwrite: false
    # datascripts:
    # - avi-datascript-redirect-app1
    # wafPolicy: avi-waf-policy
    # applicationProfile: avi-app-ref
    # analyticsProfile: avi-analytics-ref
    # errorPageProfile: avi-errorpage-ref
    # analyticsPolicy: # optional
    #   fullClientLogs:
    #     enabled: true
    #     throttle: HIGH
    #   logAllHeaders: true
    # tcpSettings:
    #   listeners:
    #   - port: 8081
    #   - port: 6443
    #     enableSSL: true
    #   loadBalancerIP: 10.10.10.1
    # aliases: # optional
    # -  bar.com
    # -  baz.com
